name: Update JSON on Release

on:
  release:
    types: [published]

jobs:
  update-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: main 

      - name: Update update.json
        run: |
          VERSION="${{ github.event.release.tag_name }}"
          URL="https://github.com/${{ github.repository }}/releases/download/${VERSION}/SpecTrum.exe"
          jq --arg v "$VERSION" --arg u "$URL" '.version = $v | .url = $u' update.json > tmp.json && mv tmp.json update.json

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add update.json
          git commit -m "Auto-update version to ${{ github.event.release.tag_name }}"
          # Пушим явно в ветку main
          git push origin main
